spring.application.name=AccountFlow
spring.datasource.url=jdbc:postgresql://localhost:5432/AccountFlow
spring.datasource.username=postgres
spring.datasource.password=admin12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Optional: Enable logging to help debug view resolution issues
logging.level.org.springframework.web.servlet=DEBUG
spring.security.enabled=false
